app.controller("SearchCtrl", function($scope, $http){

	$scope.cidades = [

      	{nome: 'Bandeirante', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Barra Bonita', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Belmonte', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Descanso', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Guaraciaba', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Paraíso ', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'São Miguel do Oeste ', codigo: '01', adr: 'São Miguel do Oeste'},
      	{nome: 'Bom Jesus do Oeste ', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Flor do Sertão', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Iraceminha', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Maravilha', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Modelo', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Pinhalzinho', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Romelândia', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Santa Terezinha do Progresso', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Saltinho', codigo: '02', adr: 'Maravilha'},
      	{nome: 'São Miguel da Boa Vista', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Saudades', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Serra Alta', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Sul Brasil', codigo: '02', adr: 'Maravilha'},
      	{nome: 'Campo Erê', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'Coronel Martins', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'Galvão', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'Novo Horizonte', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'São Bernardino', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'Jupiá', codigo: '03', adr: 'São Lourenço do Oeste'},
      	{nome: 'Águas Frias', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Caxambu do Sul', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Chapecó', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Cordilheira Alta', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Coronel Freitas', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Guatambu', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Nova Erechim', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Nova Itaberaba', codigo: '04', adr: 'São Lourenço do Oeste'},
      	{nome: 'Abelardo Luz', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Bom Jesus', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Entre Rios', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Faxinal do Guedes', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Ipuaçu', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Lajeado Grande', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Marema', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Ouro Verde', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Passos Maia', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Ponte Serrada', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'São Domingos', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Vargeão', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Xanxerê', codigo: '05', adr: 'Xanxerê'},
      	{nome: 'Alto Bela Vista', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Concórdia', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Ipira', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Irani', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Peritiba', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Piratuba ', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Presidente Castelo Branco ', codigo: '06', adr: 'Concórdia'},
      	{nome: 'Água Doce', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Capinzal', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Catanduvas', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Erval Velho', codigo: '07', adr: 'Joaçaba'},
      	{nome: "Herval d'Oeste", codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Ibicaré', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Jaborá', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Joaçaba', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Lacerdópolis', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Luzerna', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Ouro', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Treze Tílias ', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Vargem Bonita', codigo: '07', adr: 'Joaçaba'},
      	{nome: 'Abdon Batista', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Brunópolis', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Campos Novos', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Celso Ramos', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Ibiam', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Monte Carlo', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Vargem', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Zortéa', codigo: '08', adr: 'Campos Novos'},
      	{nome: 'Arroio Trinta', codigo: '09', adr: 'Videira'},
      	{nome: 'Fraiburgo', codigo: '09', adr: 'Videira'},
      	{nome: 'Iomerê', codigo: '09', adr: 'Videira'},
      	{nome: 'Pinheiro Preto', codigo: '09', adr: 'Videira'},
      	{nome: 'Salto Veloso', codigo: '09', adr: 'Videira'},
      	{nome: 'Tangará', codigo: '09', adr: 'Videira'},
      	{nome: 'Videira', codigo: '09', adr: 'Videira'},
      	{nome: 'Caçador', codigo: '10', adr: 'Caçador'},
      	{nome: 'Calmon', codigo: '10', adr: 'Caçador'},
      	{nome: 'Lebon Régis', codigo: '10', adr: 'Caçador'},
      	{nome: 'Matos Costa', codigo: '10', adr: 'Caçador'},
      	{nome: 'Rio das Antas', codigo: '10', adr: 'Caçador'},
      	{nome: 'Timbó Grande', codigo: '10', adr: 'Caçador'},
      	{nome: 'Macieira', codigo: '10', adr: 'Caçador'},
      	{nome: 'Curitibanos', codigo: '11', adr: 'Curitibanos'},
      	{nome: 'Frei Rogério', codigo: '11', adr: 'Curitibanos'},
      	{nome: 'Ponte Alta do Norte', codigo: '11', adr: 'Curitibanos'},
      	{nome: 'Santa Cecília', codigo: '11', adr: 'Curitibanos'},
      	{nome: 'São Cristóvão do Sul', codigo: '11', adr: 'Curitibanos'},
      	{nome: 'Agrolândia', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Agronômica', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Braço do Trombudo', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Laurentino', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Rio do Oeste', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Rio do Sul', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Trombudo Central', codigo: '12', adr: 'Rio do Sul'},
      	{nome: 'Alfredo Wagner', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Atalanta', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Aurora', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Chapadão do Lageado', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Imbuia', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Ituporanga', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Leoberto Leal', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Petrolândia', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Vidal Ramos', codigo: '13', adr: 'Ituporanga'},
      	{nome: 'Apiúna', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Dona Emma', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Ibirama', codigo: '14', adr: 'Ibirama'},
      	{nome: 'José Boiteux', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Lontras', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Presidente Getúlio', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Presidente Nereu', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Vitor Meirelles', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Witmarsum', codigo: '14', adr: 'Ibirama'},
      	{nome: 'Blumenau', codigo: '15', adr: 'Blumenau'},
      	{nome: 'Gaspar', codigo: '15', adr: 'Blumenau'},
      	{nome: 'Ilhota', codigo: '15', adr: 'Blumenau'},
      	{nome: 'Luís Alves', codigo: '15', adr: 'Blumenau'},
      	{nome: 'Pomerode', codigo: '15', adr: 'Blumenau'},
      	{nome: 'Botuverá', codigo: '16', adr: 'Brusque'},
      	{nome: 'Brusque', codigo: '16', adr: 'Brusque'},
      	{nome: 'Canelinha', codigo: '16', adr: 'Brusque'},
      	{nome: 'Guabiruba', codigo: '16', adr: 'Brusque'},
      	{nome: 'Major Gercino', codigo: '16', adr: 'Brusque'},
      	{nome: 'Nova Trento', codigo: '16', adr: 'Brusque'},
      	{nome: 'São João Batista', codigo: '16', adr: 'Brusque'},
      	{nome: 'Tijucas', codigo: '16', adr: 'Brusque'},
      	{nome: 'Balneário Camboriú', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Bombinhas', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Camboriú', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Itajaí', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Itapema', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Navegantes', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Penha', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Balneário Piçarras', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Porto Belo', codigo: '17', adr: 'Itajaí'},
      	{nome: 'Garopaba', codigo: '18', adr: 'Laguna'},
      	{nome: 'Imaruí', codigo: '18', adr: 'Laguna'},
      	{nome: 'Imbituba', codigo: '18', adr: 'Laguna'},
      	{nome: 'Laguna', codigo: '18', adr: 'Laguna'},
      	{nome: 'Paulo Lopes', codigo: '18', adr: 'Laguna'},
      	{nome: 'Pescaria Brava', codigo: '18', adr: 'Laguna'},
      	{nome: 'Capivari de Baixo', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Gravatal', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Jaguaruna', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Pedras Grandes', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Sangão', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Treze de Maio', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Tubarão', codigo: '19', adr: 'Tubarão'},
      	{nome: 'Balneário Rincão', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Cocal do Sul', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Criciúma', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Forquilhinha', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Içara', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Lauro Müller', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Morro da Fumaça', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Nova Veneza', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Orleans', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Siderópolis', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Treviso', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Urussanga', codigo: '20', adr: 'Criciúma'},
      	{nome: 'Araranguá', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Balneário Arroio do Silva', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Balneário Gaivota', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Ermo', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Jacinto Machado', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Maracajá', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Meleiro', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Morro Grande', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Passo de Torres', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Praia Grande', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Santa Rosa do Sul', codigo: '21', adr: 'Araranguá'},
      	{nome: 'São João do Sul', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Sombrio', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Timbé do Sul', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Turvo', codigo: '21', adr: 'Araranguá'},
      	{nome: 'Araquari', codigo: '22', adr: 'Joinville'},
      	{nome: 'Balneário Barra do Sul', codigo: '22', adr: 'Joinville'},
      	{nome: 'Barra Velha', codigo: '22', adr: 'Joinville'},
      	{nome: 'Garuva', codigo: '22', adr: 'Joinville'},
      	{nome: 'Itapoá', codigo: '22', adr: 'Joinville'},
      	{nome: 'Joinville', codigo: '22', adr: 'Joinville'},
      	{nome: 'São Francisco do Sul', codigo: '22', adr: 'Joinville'},
      	{nome: 'São João do Itaperiu', codigo: '22', adr: 'Joinville'},
      	{nome: 'Corupá', codigo: '23', adr: 'Jaraguá do Sul'},
      	{nome: 'Guaramirim', codigo: '23', adr: 'Jaraguá do Sul'},
      	{nome: 'Jaraguá do Sul', codigo: '23', adr: 'Jaraguá do Sul'},
      	{nome: 'Massaranduba ', codigo: '23', adr: 'Jaraguá do Sul'},
      	{nome: 'Schroeder', codigo: '23', adr: 'Jaraguá do Sul'},
      	{nome: 'Campo Alegre', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Itaiópolis', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Mafra', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Monte Castelo', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Papanduva', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Rio Negrinho', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'São Bento do Sul', codigo: '24', adr: 'Jaraguá do Sul'},
      	{nome: 'Bela Vista do Toldo', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Canoinhas', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Irineópolis', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Major Vieira', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Porto União', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Três Barras', codigo: '25', adr: 'Canoinhas'},
      	{nome: 'Anita Garibaldi', codigo: '26', adr: 'Lages'},
      	{nome: 'Bocaina do Sul', codigo: '26', adr: 'Lages'},
      	{nome: 'Campo Belo do Sul', codigo: '26', adr: 'Lages'},
      	{nome: 'Capão Alto', codigo: '26', adr: 'Lages'},
      	{nome: 'Cerro Negro', codigo: '26', adr: 'Lages'},
      	{nome: 'Correia Pinto', codigo: '26', adr: 'Lages'},
      	{nome: 'Lages', codigo: '26', adr: 'Lages'},
      	{nome: 'Otacílio Costa', codigo: '26', adr: 'Lages'},
      	{nome: 'Painel', codigo: '26', adr: 'Lages'},
      	{nome: 'Palmeira', codigo: '26', adr: 'Lages'},
      	{nome: 'Ponte Alta', codigo: '26', adr: 'Lages'},
      	{nome: 'São José do Cerrito', codigo: '26', adr: 'Lages'},
      	{nome: 'Bom Jardim da Serra', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'Bom Retiro', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'Rio Rufino', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'São Joaquim', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'Urubici', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'Urupema', codigo: '27', adr: 'São Joaquim'},
      	{nome: 'Águas de Chapecó', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Caibi', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Cunha Porã', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Cunhataí', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Mondaí', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Palmitos', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Riqueza', codigo: '28', adr: 'Palmitos'},
      	{nome: 'São Carlos', codigo: '28', adr: 'Palmitos'},
      	{nome: 'Anchieta', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'Dionísio Cerqueira', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'Guarujá do Sul', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'Palma Sola', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'Princesa', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'São José do Cedro', codigo: '29', adr: 'Dionísio Cerqueira'},
      	{nome: 'Iporã do Oeste', codigo: '30', adr: 'Itapiranga'},
      	{nome: 'Itapiranga', codigo: '30', adr: 'Itapiranga'},
      	{nome: 'Santa Helena', codigo: '30', adr: 'Itapiranga'},
      	{nome: 'São João do Oeste', codigo: '30', adr: 'Itapiranga'},
      	{nome: 'Tunápolis', codigo: '30', adr: 'Itapiranga'},
      	{nome: 'Formosa do Sul', codigo: '31', adr: 'Quilombo'},
      	{nome: 'Irati', codigo: '31', adr: 'Quilombo'},
      	{nome: 'Jardinópolis', codigo: '31', adr: 'Quilombo'},
      	{nome: 'Quilombo', codigo: '31', adr: 'Quilombo'},
      	{nome: 'Santiago do Sul', codigo: '31', adr: 'Quilombo'},
      	{nome: 'União do Oeste', codigo: '31', adr: 'Quilombo'},
      	{nome: 'Arabutã', codigo: '32', adr: 'Seara'},
      	{nome: 'Arvoredo', codigo: '32', adr: 'Seara'},
      	{nome: 'Ipumirim', codigo: '32', adr: 'Seara'},
      	{nome: 'Itá', codigo: '32', adr: 'Seara'},
      	{nome: 'Lindoia do Sul', codigo: '32', adr: 'Seara'},
      	{nome: 'Paial', codigo: '32', adr: 'Seara'},
      	{nome: 'Seara', codigo: '32', adr: 'Seara'},
      	{nome: 'Xavantina', codigo: '32', adr: 'Seara'},
      	{nome: 'Mirim Doce', codigo: '33', adr: 'Taió'},
      	{nome: 'Pouso Redondo', codigo: '33', adr: 'Taió'},
      	{nome: 'Rio do Campo', codigo: '33', adr: 'Taió'},
      	{nome: 'Salete', codigo: '33', adr: 'Taió'},
      	{nome: 'Santa Terezinha', codigo: '33', adr: 'Taió'},
      	{nome: 'Taió', codigo: '33', adr: 'Taió'},
      	{nome: 'Ascurra', codigo: '34', adr: 'Timbó'},
      	{nome: 'Benedito Novo', codigo: '34', adr: 'Timbó'},
      	{nome: 'Doutor Pedrinho', codigo: '34', adr: 'Timbó'},
      	{nome: 'Indaial', codigo: '34', adr: 'Timbó'},
      	{nome: 'Rio dos Cedros', codigo: '34', adr: 'Timbó'},
      	{nome: 'Rodeio', codigo: '34', adr: 'Timbó'},
      	{nome: 'Timbó', codigo: '34', adr: 'Timbó'},
      	{nome: 'Armazém', codigo: '35', adr: 'Timbó'},
      	{nome: 'Braço do Norte', codigo: '35', adr: 'Timbó'},
      	{nome: 'Grão Pará', codigo: '35', adr: 'Timbó'},
      	{nome: 'Rio Fortuna', codigo: '35', adr: 'Timbó'},
      	{nome: 'Santa Rosa de Lima', codigo: '35', adr: 'Timbó'},
      	{nome: 'São Ludgero', codigo: '35', adr: 'Timbó'},
      	{nome: 'São Martinho', codigo: '35', adr: 'Timbó'}
    ];
});